# Generated by Django 2.2.14 on 2021-11-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=200, null=True)),
                ('height', models.CharField(max_length=200, null=True)),
                ('weight', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('lifestyle', models.CharField(choices=[('sedentry', 'sedentry'), ('moderately active', 'moderately active'), ('active', 'active')], max_length=200, null=True)),
                ('goals', models.CharField(choices=[('weightloss', 'weightloss'), ('musclegain', 'musclegain'), ('healthyeating', 'healthyeating')], max_length=200, null=True)),
                ('foodprefence', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('NonVegetarian', 'NonVegetarian'), ('Vegan', 'Vegan')], max_length=200, null=True)),
            ],
        ),
    ]
