# Generated by Django 2.2.14 on 2021-11-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_info_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='height',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='weight',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
