# Generated by Django 2.2.14 on 2021-11-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211113_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
