# Generated by Django 2.2.14 on 2021-11-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211114_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
