# Generated by Django 2.2.14 on 2021-11-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211116_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
