# Generated by Django 2.2.14 on 2021-11-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211116_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='age',
            field=models.FloatField(null=True),
        ),
    ]
