# Generated by Django 2.2.14 on 2021-11-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211117_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=200, null=True),
        ),
    ]
